import type { Metadata } from "next";

import "./globals.css";
import { marcellus } from "./fonts";

export const metadata: Metadata = {
  title: "Pedro Costa",
  description: "Generated by Next, Developed by me :P",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={marcellus.className}
      data-theme={"dark"}
      suppressHydrationWarning
    >
      <body className="bg-zinc-100 dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100 px-4 py-20 md:px-16 lg:px-0">
        {children}
      </body>
    </html>
  );
}
