import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";
import { marcellus } from "./fonts";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Pedro Costa",
  description: "Generated by Next, Developed by me :P",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={marcellus.className}
      data-theme={"dark"}
      suppressHydrationWarning
    >
      <Analytics />
      <body className="bg-zinc-100 dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100">
        {children}
        <Footer />
      </body>
    </html>
  );
}
